export const produtos = [
    {
        id: 0,
        tipo: 'Caneca',
        nmProduto: 'Caneca mensagem biblica',
        img: 'https://img.elo7.com.br/product/original/3B1D793/caneca-personalizavel-com-frase-biblica-325ml-caneca-catolica.jpg',
        descricao: '',
        vlProduto: 22.49,
        prontaEntrega: false,
    },
    {
        id: 1,
        tipo: 'Camiseta',
        nmProduto: 'Camiseta Jesus te ama',
        img: 'https://i.pinimg.com/originals/c7/ac/a3/c7aca31c5cdc084e9fe435035f05e65d.jpg',
        descricao: 'Camiseta unisex',
        vlProduto: 39.99,
        prontaEntrega: true,
    },
    {
        id: 2,
        tipo: 'Caneca',
        nmProduto: 'Caneca mensagem biblica',
        img: 'https://img.elo7.com.br/product/original/3B1D793/caneca-personalizavel-com-frase-biblica-325ml-caneca-catolica.jpg',
        descricao: '',
        vlProduto: 22.49,
        prontaEntrega: false,
    },
    {
        id: 3,
        tipo: 'Camiseta',
        nmProduto: 'Camiseta Jesus te ama',
        img: 'https://i.pinimg.com/originals/c7/ac/a3/c7aca31c5cdc084e9fe435035f05e65d.jpg',
        descricao: 'Camiseta unisex',
        vlProduto: 39.99,
        prontaEntrega: true,
    },
    {
        id: 4,
        tipo: 'Caneca',
        nmProduto: 'Caneca mensagem biblica',
        img: 'https://img.elo7.com.br/product/original/3B1D793/caneca-personalizavel-com-frase-biblica-325ml-caneca-catolica.jpg',
        descricao: '',
        vlProduto: 22.49,
        prontaEntrega: false,
    },
    {
        id: 5,
        tipo: 'Camiseta',
        nmProduto: 'Camiseta Jesus te ama',
        img: 'https://i.pinimg.com/originals/c7/ac/a3/c7aca31c5cdc084e9fe435035f05e65d.jpg',
        descricao: 'Camiseta unisex',
        vlProduto: 39.99,
        prontaEntrega: true,
    },
    {
        id: 6,
        tipo: 'Caneca',
        nmProduto: 'Caneca mensagem biblica',
        img: 'https://img.elo7.com.br/product/original/3B1D793/caneca-personalizavel-com-frase-biblica-325ml-caneca-catolica.jpg',
        descricao: '',
        vlProduto: 22.49,
        prontaEntrega: false,
    },
    {
        id: 7,
        tipo: 'Camiseta',
        nmProduto: 'Camiseta Jesus te ama',
        img: 'https://i.pinimg.com/originals/c7/ac/a3/c7aca31c5cdc084e9fe435035f05e65d.jpg',
        descricao: 'Camiseta unisex',
        vlProduto: 39.99,
        prontaEntrega: true,
    },
];